import { sb, $, esc, checked, signed, toast, dialog, attempt, bind, upload } from "./api.js";
import { startVideo, stopVideo } from "./video.js";
let channel, timer, current=null, generation=0, recorder, recordingStream, loading=false, lastSeenMessageId=null;

function dateLabel(value){const d=new Date(value),now=new Date(),today=new Date(now.getFullYear(),now.getMonth(),now.getDate()),day=new Date(d.getFullYear(),d.getMonth(),d.getDate()),diff=Math.round((today-day)/86400000);return diff===0?"Hoy":diff===1?"Ayer":d.toLocaleDateString("es-CO",{day:"numeric",month:"long",year:d.getFullYear()===now.getFullYear()?undefined:"numeric"});}
function beep(){try{const C=window.AudioContext||window.webkitAudioContext;if(!C)return;const ctx=new C(),o=ctx.createOscillator(),g=ctx.createGain();o.frequency.value=620;g.gain.setValueAtTime(.025,ctx.currentTime);g.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+.12);o.connect(g).connect(ctx.destination);o.start();o.stop(ctx.currentTime+.12);}catch{}}
export function stopChat(){generation++;if(channel){sb.removeChannel(channel);channel=null;}clearInterval(timer);timer=null;current=null;if(recorder?.state==="recording")recorder.stop();recordingStream?.getTracks().forEach(t=>t.stop());recordingStream=null;stopVideo();}

export async function openChats(state,requested){
  const token=generation;
  const [convR,msgR]=await Promise.all([
    sb.from("conversations").select("*,creators(stage_name,user_id)").order("updated_at",{ascending:false}),
    sb.from("messages").select("id,conversation_id,sender_id,body,created_at,read_at").order("created_at",{ascending:false}).limit(800),
  ]);
  const list=checked(convR), messages=checked(msgR); if(token!==generation)return;
  const last=new Map(),unread=new Map();
  for(const m of messages){if(!last.has(m.conversation_id))last.set(m.conversation_id,m);if(!m.read_at&&m.sender_id!==state.user.id)unread.set(m.conversation_id,(unread.get(m.conversation_id)||0)+1);}
  $("main").innerHTML=`<div class="page-title"><div><div class="eyebrow">MENSAJES</div><h1>Conversaciones en tiempo real.</h1><p>Mensajes y notificaciones se mantienen separados.</p></div><button id="chatSound">${state.profile.chat_sound_enabled===false?"🔇 Sonido silenciado":"🔊 Sonido activo"}</button></div><div class="chat-layout"><div id="conversationList" class="chat-list">${list.map(c=>{const lm=last.get(c.id),n=unread.get(c.id)||0;return `<button data-conversation="${c.id}"><div class="row between"><b>${esc(c.creators?.stage_name||"Conversación")}</b>${n?`<span class="badge">${n>99?"99+":n}</span>`:""}</div><span class="small muted">${esc(lm?.body||"Sin mensajes todavía")}</span><br><span class="small muted">${lm?new Date(lm.created_at).toLocaleString("es-CO"):""}</span></button>`;}).join("")||'<p class="small muted">Aún no tienes conversaciones.</p>'}</div><section id="chatRoom" class="chat-room"><div class="empty">Selecciona una conversación.</div></section></div>`;
  bind("chatSound",async()=>{const value=state.profile.chat_sound_enabled===false;checked(await sb.from("profiles").update({chat_sound_enabled:value}).eq("id",state.user.id));state.profile.chat_sound_enabled=value;$("chatSound").textContent=value?"🔊 Sonido activo":"🔇 Sonido silenciado";});
  document.querySelectorAll("[data-conversation]").forEach(b=>b.onclick=()=>attempt(()=>selectConversation(state,list.find(c=>c.id===b.dataset.conversation))));
  if(requested){const c=list.find(c=>c.id===requested);if(c)await selectConversation(state,c);}
}

async function selectConversation(state,c){
  if(!c)return;if(channel)await sb.removeChannel(channel);clearInterval(timer);await stopVideo();current=c.id;
  const admin=state.profile.role==="admin";let moderationSession=null;
  if(admin){
    const existing=checked(await sb.from("chat_moderation_sessions").select("*").eq("conversation_id",c.id).eq("admin_id",state.user.id).is("left_at",null).gt("expires_at",new Date().toISOString()).order("entered_at",{ascending:false}).limit(1));
    moderationSession=existing[0]||null;
    if(!moderationSession){const reason=prompt("Motivo de revisión administrativa. Se notificará a los participantes:");if(!reason){current=null;return;}const sid=checked(await sb.rpc("admin_enter_chat",{p_conversation_id:c.id,p_reason:reason}));moderationSession={id:sid,can_intervene:false};}
  }
  const capability=admin?{media:false,peer_name:c.creators?.stage_name}:checked(await sb.rpc("conversation_capabilities",{cid:c.id}));
  async function requireCapability(key){if(current!==c.id)return false;const fresh=checked(await sb.rpc("conversation_capabilities",{cid:c.id}));if(fresh[key]===true)return true;dialog('<span class="badge diamond">Diamante</span><h2>Esta función requiere Diamante.</h2><p>Multimedia y videollamadas se habilitan únicamente con permisos reales del plan.</p><button id="chatUpgrade" class="primary">Conocer Diamante</button>');bind("chatUpgrade",()=>{$("dialog").close();location.hash="plans";});return false;}
  const adminControls=()=>`<div class="notice small"><b>Moderación CARLÉA</b> · ${moderationSession?.can_intervene?"Intervención habilitada":"SOLO LECTURA"}. El acceso está auditado y es visible para participantes.<div class="row">${!moderationSession?.can_intervene?'<button id="enableModeration" class="primary">Intervenir como moderador</button>':""}<button id="leaveModeration">Salir de moderación</button></div></div>${moderationSession?.can_intervene?'<form id="moderationCompose" class="chat-compose"><textarea id="moderationText" maxlength="4000" placeholder="Mensaje de Moderación CARLÉA…"></textarea><button class="primary" type="submit">Enviar como Moderación CARLÉA</button></form>':""}`;
  $("chatRoom").innerHTML=`<div class="chat-head"><div><b>${esc(capability.peer_name||c.creators?.stage_name||"Conversación")}</b><br><span id="connectionStatus" class="inline-status">Conectando…</span><span id="typingStatus" class="small muted"></span></div>${!admin&&c.user_id===state.user.id?`<button id="requestVideo" ${capability.media?"":'title="Disponible en Diamante"'}>▣ Videollamada</button>`:""}</div><div id="callArea"></div><div id="chatFeed" class="chat-feed" aria-live="polite"></div>${admin?adminControls():`<form id="compose" class="chat-compose"><textarea id="messageText" maxlength="4000" aria-label="Mensaje" placeholder="Escribe un mensaje…"></textarea><div class="row between"><div class="row"><button type="button" id="emoji">☺</button><button type="button" id="attach">＋</button><button type="button" id="record">♩</button><input class="hidden" id="attachment" type="file" accept="image/jpeg,image/png,image/webp,video/mp4,video/webm,audio/webm,audio/ogg,audio/mp4"></div><button class="primary" type="submit">Enviar</button></div></form>`}`;
  let latestSignature="",callSignature="",presenceTyping=false,typingTimer;
  async function refresh(){if(current!==c.id||loading)return;loading=true;try{
    const messages=checked(await sb.from("messages").select("*").eq("conversation_id",c.id).order("created_at",{ascending:false}).limit(250)).reverse();if(current!==c.id)return;
    const newest=messages[messages.length-1];if(lastSeenMessageId&&newest&&newest.id!==lastSeenMessageId&&newest.sender_id!==state.user.id&&state.profile.chat_sound_enabled!==false&&document.hidden)beep();if(newest)lastSeenMessageId=newest.id;
    const sig=messages.map(m=>`${m.id}:${m.read_at||""}`).join();if(sig!==latestSignature){latestSignature=sig;const html=[];let group="";for(const m of messages){const dl=dateLabel(m.created_at);if(dl!==group){group=dl;html.push(`<div class="small muted" style="text-align:center;margin:14px 0">${esc(dl)}</div>`);}let media="";if(m.attachment_path){try{const url=await signed("chat-private",m.attachment_path);media=m.attachment_kind==="image"?`<img src="${esc(url)}" alt="Foto compartida">`:m.attachment_kind==="audio"?`<audio controls src="${esc(url)}"></audio>`:`<video controls playsinline src="${esc(url)}"></video>`;}catch{media="<span>Archivo no disponible para tu acceso actual.</span>";}}const moderator=m.message_kind==="moderation";html.push(`<div class="message ${m.sender_id===state.user.id?"mine":""} ${moderator?"moderation-message":""}">${moderator?'<b>Moderación CARLÉA</b><br>':""}${media}${esc(m.body)}<small>${new Date(m.created_at).toLocaleTimeString("es-CO",{hour:"2-digit",minute:"2-digit"})}${m.read_at?" · leído":""}</small></div>`);}if($("chatFeed")){$("chatFeed").innerHTML=html.join("")||'<p class="muted small">Inicia una conversación respetuosa.</p>';$("chatFeed").scrollTop=$("chatFeed").scrollHeight;}}
    if(!admin)await sb.rpc("mark_conversation_read",{p_conversation_id:c.id});
    if(!admin){const calls=checked(await sb.from("video_calls").select("*").eq("conversation_id",c.id).order("created_at",{ascending:false}).limit(1));const call=calls[0],signature=call?`${call.id}:${call.status}:${call.payment_status}:${call.started_at||""}:${call.ended_at||""}`:"";if(signature!==callSignature){callSignature=signature;await showCall(call,state,c,refresh);}}
  }catch(e){if($("connectionStatus"))$("connectionStatus").textContent="Sin actualización: "+e.message;}finally{loading=false;}}
  await refresh();
  channel=sb.channel("conversation-"+c.id,{config:{presence:{key:state.user.id}}}).on("postgres_changes",{event:"INSERT",schema:"public",table:"messages",filter:"conversation_id=eq."+c.id},refresh).on("postgres_changes",{event:"*",schema:"public",table:"video_calls",filter:"conversation_id=eq."+c.id},refresh).on("presence",{event:"sync"},()=>{const all=channel.presenceState(),typing=Object.entries(all).some(([uid,arr])=>uid!==state.user.id&&arr.some(x=>x.typing));if($("typingStatus"))$("typingStatus").textContent=typing?" · escribiendo…":"";}).subscribe(async status=>{if($("connectionStatus"))$("connectionStatus").textContent=status==="SUBSCRIBED"?"Conectado · tiempo real":"Actualización de respaldo activa";if(status==="SUBSCRIBED")await channel.track({user_id:state.user.id,typing:false,online_at:new Date().toISOString()});});
  timer=setInterval(()=>{if(!document.hidden)refresh();},5000);
  if(admin){
    bind("enableModeration",async()=>{checked(await sb.rpc("admin_enable_chat_intervention",{p_session_id:moderationSession.id}));moderationSession.can_intervene=true;await selectConversation(state,c);});
    bind("leaveModeration",async()=>{checked(await sb.rpc("admin_leave_chat",{p_session_id:moderationSession.id}));location.hash="admin/chats";});
    if($("moderationCompose"))$("moderationCompose").onsubmit=e=>{e.preventDefault();attempt(async()=>{const body=$("moderationText").value.trim();if(!body)return;checked(await sb.rpc("admin_send_moderation_message",{p_session_id:moderationSession.id,p_body:body}));$("moderationText").value="";await refresh();});};
    return;
  }
  $("messageText").addEventListener("input",()=>{if(!channel)return;clearTimeout(typingTimer);if(!presenceTyping){presenceTyping=true;channel.track({user_id:state.user.id,typing:true});}typingTimer=setTimeout(()=>{presenceTyping=false;channel.track({user_id:state.user.id,typing:false});},1200);});
  $("compose").onsubmit=async e=>{e.preventDefault();const body=$("messageText").value.trim();if(!body)return;const b=e.target.querySelector("[type=submit]");b.disabled=true;await attempt(async()=>{if(!(await requireCapability("canSendText")))return;checked(await sb.from("messages").insert({conversation_id:c.id,sender_id:state.user.id,body}));$("messageText").value="";presenceTyping=false;channel.track({user_id:state.user.id,typing:false});await refresh();});b.disabled=false;};
  bind("emoji",()=>{$("messageText").value+=" 😊";$("messageText").focus();});bind("attach",async()=>{if(await requireCapability("canSendMedia"))$("attachment").click();});
  async function sendAttachment(file){const permission=file.type.startsWith("audio")?"canSendAudio":"canSendMedia";if(!(await requireCapability(permission)))return;const path=await upload("chat-private",file,c.id+"/"+state.user.id,15*1024*1024),kind=file.type.startsWith("image")?"image":file.type.startsWith("audio")?"audio":"video";const r=await sb.from("messages").insert({conversation_id:c.id,sender_id:state.user.id,body:kind==="audio"?"Nota de voz":kind==="image"?"Foto":"Video",attachment_path:path,attachment_kind:kind});if(r.error){await sb.storage.from("chat-private").remove([path]);throw r.error;}await refresh();}
  $("attachment").onchange=e=>attempt(async()=>{if(e.target.files[0])await sendAttachment(e.target.files[0]);e.target.value="";});
  bind("record",async()=>{if(recorder?.state==="recording"){recorder.stop();return;}if(!(await requireCapability("canSendAudio")))return;if(!navigator.mediaDevices||!window.MediaRecorder)throw Error("Este navegador no admite notas de voz.");recordingStream=await navigator.mediaDevices.getUserMedia({audio:true});const type=["audio/webm","audio/ogg","audio/mp4"].find(t=>MediaRecorder.isTypeSupported(t));recorder=new MediaRecorder(recordingStream,type?{mimeType:type}:{});const chunks=[];recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data);};recorder.onstop=()=>{recordingStream?.getTracks().forEach(t=>t.stop());if($("record"))$("record").textContent="♩";if(current===c.id)attempt(()=>sendAttachment(new File(chunks,"nota-de-voz",{type:recorder.mimeType.split(";")[0]})));};recorder.start();$("record").textContent="■ Detener";setTimeout(()=>{if(recorder?.state==="recording")recorder.stop();},60000);});
  bind("requestVideo",async()=>{if(!(await requireCapability("canRequestVideoCall")))return;dialog(`<div class="eyebrow">VIDEOLLAMADA</div><h2>Selecciona la duración</h2><form id="videoPurchase"><label class="field">Duración<select name="duration"><option value="30">30 minutos — $49.900 COP</option><option value="60" selected>60 minutos — $79.900 COP · Recomendado</option><option value="90">90 minutos — $99.900 COP · Mejor valor</option></select></label><label class="field">Horario preferido<input name="when" type="datetime-local" required></label><div class="notice"><b>En esta versión el pago será validado manualmente.</b> La solicitud no habilita la sala hasta la aprobación administrativa y la aceptación de la creadora.</div><button class="primary full" type="submit">Continuar al pago</button></form>`);const f=$("videoPurchase");f.onsubmit=e=>{e.preventDefault();attempt(async()=>{const fd=new FormData(f);checked(await sb.rpc("request_video_call_purchase",{p_conversation_id:c.id,p_duration_minutes:Number(fd.get("duration")),p_requested_start_at:new Date(fd.get("when")).toISOString()}));$("dialog").close();toast("Solicitud de pago creada. Estado: PENDIENTE.");await refresh();});};});
}

async function showCall(call,state,c,refresh){
  if(!$("callArea"))return;if(!call||["ended","declined"].includes(call.status)){await stopVideo(false);$("callArea").innerHTML=call?.status==="declined"?'<p class="small muted" style="padding:10px">La solicitud no fue aceptada.</p>':"";return;}
  const isCreator=c.creators?.user_id===state.user.id,paymentApproved=call.payment_status==="approved";
  const desc=!paymentApproved?"Pago pendiente de validación administrativa.":call.status==="requested"?(isCreator?"Pago aprobado. Responde la solicitud de videollamada.":"Pago aprobado. Esperando respuesta de la creadora."):"Solicitud aceptada. El temporizador empieza únicamente cuando la llamada realmente inicia.";
  $("callArea").innerHTML=`<div class="notice small"><b>${call.duration_minutes||"—"} min · ${call.price_cop?new Intl.NumberFormat("es-CO",{style:"currency",currency:"COP",maximumFractionDigits:0}).format(call.price_cop):""}</b><br>${desc}<div class="row">${paymentApproved&&call.status==="requested"&&isCreator?'<button id="acceptCall" class="primary">Aceptar</button><button id="proposeCall">Proponer horario</button><button id="declineCall">Rechazar</button>':""}${paymentApproved&&call.status==="accepted"?'<button id="joinCall" class="primary">Entrar a videollamada</button>':""}<button id="endCall">${call.status==="requested"?"Cancelar":"Finalizar"}</button></div><div id="videoMount"></div></div>`;
  bind("acceptCall",async()=>{checked(await sb.rpc("creator_respond_video_call",{p_call_id:call.id,p_decision:"accepted",p_proposed_start_at:null}));await refresh();});
  bind("proposeCall",async()=>{const v=prompt("Nuevo horario (AAAA-MM-DD HH:MM):");if(!v)return;checked(await sb.rpc("creator_respond_video_call",{p_call_id:call.id,p_decision:"proposed",p_proposed_start_at:new Date(v.replace(" ","T")).toISOString()}));await refresh();});
  bind("declineCall",async()=>{checked(await sb.rpc("creator_respond_video_call",{p_call_id:call.id,p_decision:"declined",p_proposed_start_at:null}));await refresh();});
  bind("endCall",async()=>{if(call.started_at)checked(await sb.rpc("finish_video_call",{p_call_id:call.id}));else if(isCreator&&paymentApproved)checked(await sb.rpc("creator_respond_video_call",{p_call_id:call.id,p_decision:"declined",p_proposed_start_at:null}));await stopVideo(false);await refresh();});
  bind("joinCall",async()=>{checked(await sb.rpc("start_video_call",{p_call_id:call.id}));const refreshed=checked(await sb.from("video_calls").select("*").eq("id",call.id).single());await startVideo(refreshed,state.user.id,"videoMount");if($("joinCall"))$("joinCall").disabled=true;});
}
